# Generated by Django 4.2.7 on 2024-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0002_task_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1024, null=True)),
                ('response_text', models.CharField(max_length=5000, null=True)),
                ('model_used', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
