# Generated by Django 4.0.7 on 2023-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('work_type', models.CharField(max_length=25)),
                ('experience_level', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=125)),
            ],
        ),
    ]
