# Generated by Django 4.0.7 on 2023-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='bid_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
