# Generated by Django 4.0.7 on 2023-08-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vid_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
