# Generated by Django 4.0.7 on 2023-08-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vid_g', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_link', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vid_g.category')),
            ],
        ),
    ]
