# Generated by Django 4.0.7 on 2023-08-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_g', '0003_alter_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_link',
        ),
        migrations.AddField(
            model_name='video',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='Media/featured_img'),
        ),
    ]
