# Generated by Django 5.0.7 on 2024-08-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dataset_instructions', models.TextField()),
                ('use_cases', models.TextField()),
            ],
        ),
    ]
