# Generated by Django 5.0.7 on 2024-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('Stat', 'Statistical Analysis'), ('Data Analysis', 'Data Analysis'), ('Customer Engagement', 'Customer Engagement'), ('Banking Sector', 'Banking Sector'), ('Large Language Models', 'Large Language Models'), ('Marketing Analysis', 'Marketing Analysis'), ('Product Management', 'Product Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
