# Generated by Django 5.0.4 on 2024-04-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
